version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wptest
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - site
  php:
    build:
      context: ./docker/php
    depends_on:
      - db
    image: williamsilva808:php-7.2
    container_name: application
    environment:
      DB_HOST: 'db:3306'
      DB_PORT: '3306'
      DB_DATABASE: 'wptest'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
      DEBUG: 'true'
    volumes:
      - ./:/var/www/html
    networks:
      - site

  web:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    networks:
      - site
networks:
  site:
    driver: bridge
volumes:
    db_data: